version: '2'
services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  mongo-backup:
    image: lifely/mongo-backup-container
    container_name: mongo-backup
    depends_on:
      - mongo
  
    environment:
      AWS_ACCESS_KEY_ID: ID
      AWS_SECRET_ACCESS_KEY: KEY
      AWS_S3_BUCKET: BUCKET
      AWS_REGION: eu-central-1
      MONGO_HOST: mongo:27017
      SCHEDULE: '* * * * *'