version: 2
jobs:
  build:
    branches:
      only:
        - develop
        
    docker:
      - image: docker:git

    working_directory: ~/container

    steps:
      - checkout
      - setup_remote_docker

      - run: |
          docker build -t lifely/mongo-backup-container:$CIRCLE_SHA1 .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push lifely/mongo-backup-container:$CIRCLE_SHA1