version: 2
jobs:
  build-and-push-to-docker:        
    docker:
      - image: docker:git

    working_directory: ~/container

    steps:
      - checkout
      - setup_remote_docker

      - run: |
          docker build -t lifely/mongo-backup-container:$CIRCLE_SHA1 .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push lifely/mongo-backup-container:$CIRCLE_SHA1

workflows:
  version: 2
  build:
    jobs:
      - build-and-push-to-docker:
          context: docker-hub-auth
          filters:
            branches:
              only: develop